groceries/urls.py
from django.urls import path
from . import views

app_name = 'groceries'
urlpatterns = [
    path('', views.index, name='index'),
    path('lend/<int:lend_id>/', views.lendItem, name='lend'),
    path('hist/<int:lend_id>/', views.itemHist, name='hist'),
    path('edit/<int:lend_id>/', views.editItem, name='edit'),
    path('del/<int:lend_id>/', views.delItem, name='del'),
    path('new/', views.newItem, name='new'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('logout/', views.logout_view, name='logout'),
]

mystuff/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('items/', include('groceries.urls')),
    path('meeting/', include('meeting.urls')),
    path('courses/', include('courses.urls')),
    path('linux/', include('linux.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceries/models.py
from django.db import models
from home.models import Teacher

class Items(models.Model):

    class Meta:
        verbose_name="设备"
        verbose_name_plural="设备"

    name = models.CharField(max_length=200)
    serial = models.CharField(max_length=20)
    value = models.IntegerField(default=0)
    position = models.CharField(max_length=20)
    status = models.IntegerField(default=0)
    note = models.CharField(max_length=200)
    owner = models.ForeignKey(Teacher, on_delete = models.CASCADE)
    def __unicode__(self):
        return self.name

class History(models.Model):
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    user = models.CharField(max_length=20)
    date = models.DateTimeField('Borrow Date')
    tel = models.CharField(max_length=20)
    note = models.CharField(max_length=200)
    back = models.DateTimeField('Return Date', blank=True, null=True)

groceries/forms.py
#-*- coding: UTF-8 -*-

from django import forms

class LendForm(forms.Form):
    username = forms.CharField(
        label='姓名',
        error_messages={'required': '姓名必须填写'} # don't work for hint messages?
        )
    telephone = forms.CharField(
        label='电话',
        )
    note = forms.CharField(
        label='备注',
        )

class NewItem(forms.Form):
    itemname = forms.CharField(
        label = '设备名称',
        )
    serial = forms.CharField(
        label = '序列号',
        )
    value = forms.CharField(
        label = '价格',
        )
    room = forms.CharField(
        label = '所在房间号',
        )
    note = forms.CharField(
        required = False,
        label = '备注',
        widget = forms.Textarea(),
        )

groceries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from .models import Items, History
from django.contrib.auth.decorators import login_required
import datetime
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from home.models import Teacher

def getTea(request):
    try:
        tea = Teacher.objects.get(uid = request.session['schoolid'])
    except Teacher.DoesNotExist:
        raise Http404("需要在Teacher表中注册")
    except KeyError:
        raise Http404("非标准用户或未登录")
    return tea

def index(request):
    tea = getTea(request)
    paginator = Paginator(Items.objects.filter(owner=tea), 25)
    page = request.GET.get('page', 1)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    return render(request, 'groceries/index.html', {'item_list': items})

from .forms import LendForm, NewItem

def lendItem(request, lend_id):
    item = get_object_or_404(Items, pk=lend_id)
    if request.method == 'POST':
        form = LendForm(request.POST)
        if form.is_valid():
            if item.status == 0:
                item.status = 1
                hist = History(item = item)
                hist.user = request.POST.get('username', '')
                hist.tel = request.POST.get('telephone', '')
                hist.note = request.POST.get('note', '')
                hist.date = timezone.now()
                hist.save()
                item.save()
            return HttpResponseRedirect(reverse('groceries:index'))
    else:
        if item.status == 1: # return the item
            item.status = 0
            item.save()
            hist = History.objects.filter(item=item).order_by('-date')
            if hist.count() >= 1:
                h = hist.first()
                h.back = timezone.now()
                h.save()
            return HttpResponseRedirect(reverse('groceries:index'))
        form = LendForm();
    return render(request, 'groceries/lend.html', {'form': form, 'f':'lend'})

def newItem(request):
    tea = getTea(request)
    if request.method == 'POST':
        form = NewItem(request.POST)
        if form.is_valid():
            item = Items(owner = tea)
            item.name = request.POST.get('itemname','')
            item.serial = request.POST.get('serial','')
            item.value = request.POST.get('value','')
            item.position = request.POST.get('room','')
            item.note = request.POST.get('note','')
            item.save()
            return HttpResponseRedirect('/items/')
    else:
        form = NewItem();
    return render(request, 'groceries/lend.html', {'form': form, 'f':'new'})

def editItem(request, lend_id):
    item = get_object_or_404(Items, pk=lend_id)
    tea = getTea(request)
    if (tea != item.owner):
        raise Http404("不能修改其他用户设备")
    if request.method == 'POST':
        form = NewItem(request.POST)
        if form.is_valid():
            item.name = request.POST.get('itemname','')
            item.serial = request.POST.get('serial','')
            item.value = request.POST.get('value','')
            item.position = request.POST.get('room','')
            item.note = request.POST.get('note','')
            item.save()
            return HttpResponseRedirect('/items/')
    else:
        form = NewItem(
            initial={'itemname': item.name,
                'serial': item.serial,
                'value': item.value,
                'room': item.position,
                'note': item.note});
    return render(request, 'groceries/lend.html', {'form': form, 'f':'new'})

def delItem(request, lend_id):
    item = get_object_or_404(Items, pk=lend_id)
    tea = getTea(request)
    if (tea != item.owner):
        raise Http404("不能删除其他用户设备")
    item.delete()
    return HttpResponseRedirect('/items/')

def itemHist(request, lend_id):
    item = get_object_or_404(Items, pk=lend_id)
    hist = History.objects.filter(item=item).order_by('-date')
    return render(request, 'groceries/hist.html', {'hist': hist})

groceries/templates/groceries/hist.html
{% extends 'nav.html' %}

{% block subtitle %}-物品历史{% endblock %}
{% block main %}
<div class="panel panel-default col-md-12">
  <!-- Default panel contents -->
  <div class="panel-heading text-center"><h2>历史</h2></div>
{% if hist %}
  <table class="table table-bordered table-striped">
    <tr><th>姓名</th><th>借出时间</th><th>联系电话</th><th>备注</th><th>归还时间</th></tr>
    {% for item in hist %}
    <tr>
    <td>{{ item.user }}</td><td> {{item.date}}</td>
    <td>{{ item.tel }}</td><td> {{item.note}}</td><td> {{item.back}}</td>
    </tr>
    {% endfor %}
  </table>
{% else %}
    <p>没有借出历史</p>
{% endif %}
</div>
{% endblock %}
{% block ac3 %}active{% endblock %}

groceries/templates/groceries/index.html
{% extends 'nav.html' %}
{% block subtitle %}-设备列表{% endblock %}
{% block main %}
<script language="JavaScript">
<!--
function SureDel(delurl)
{
	if (confirm("确定要删除这条记录?")){
        location = delurl;
	}
}
-->
</script>
<div class="panel panel-default col-md-12">
  <!-- Default panel contents -->
  <div class="panel-heading text-center"><h2>设备列表</h2></div>
{% if item_list.object_list.count %}
  <ul class="pagination">
	<li class="prev page-item{% if not item_list.has_previous %} disabled{% endif %}">
        <a class="page-link" href="{% if not item_list.has_previous %}#{% else %}?page=1{% endif %}">&laquo;</a>
    </li>
    <li class="prev page-item{% if not item_list.has_previous %} disabled{% endif %}">
        <a class="page-link" href="{% if not item_list.has_previous %}#{% else %}?page={{ item_list.previous_page_number }}{% endif %}">前一页</a>
    </li>
    {% for p in item_list.paginator.page_range %}
    {% if p > item_list.number|add:'-3' and p < item_list.number|add:'3' %}
      <li class="page-item{% if item_list.number == p %} active{% endif %}">
          <a class="page-link" href="{% if item_list.number == p %}#{% else %}?page={{ p }}{% endif %}">{{ p }}</a>
      </li>
    {% endif %}
    {% endfor %}
    <li class="last page-item{% if not item_list.has_next %} disabled{%endif %}">
        <a class="page-link" href="{% if not item_list.has_next %}#{% else %}?page={{ item_list.next_page_number }}{%endif %}">后一页</a>
    </li>
    <li class="last page-item{% if not item_list.has_next %} disabled{%endif %}">
        <a class="page-link" href="{% if not item_list.has_next %}#{% else %}?page={{ item_list.num_pages }}{%endif %}">&raquo;</a>
    </li>
    &nbsp;&nbsp;<a class="btn btn-outline-primary" href="{% url 'groceries:new' %}">新建设备</a>
  </ul>

  <table class="table table-bordered table-striped">
    <tr><th>设备名称</th><th>序列号</th><th>保存位置</th><th>备注</th><th>状态</th><th> 操作</th> </tr>
    {% for item in item_list.object_list %}
    <tr>
        <td>{{ item.name }}</td><td> {{item.serial}}</td><td> {{item.position}}</td><td>{{item.note}}</td>
    <td>{% if item.status == 0 %}正常{% else %}借出{% endif %}</td>
    <td><a class="btn btn-outline-primary" href="{% url 'groceries:hist' item.id %}">历史</a>
    <a class="btn btn-outline-primary" href="{% url 'groceries:lend' item.id %}">
        {% if item.status == 0 %}出借{% else %}归还{% endif %}</a>
    <a class="btn btn-outline-primary" href="{% url 'groceries:edit' item.id %}">修改</a>
    <a class="btn btn-outline-danger" href="javascript:SureDel('{% url 'groceries:del' item.id %}');">删除</a></td>
    </tr>
    {% endfor %}
  </table>
{% else %}
    <p>还没有任何设备</p>
    <a class="btn btn-outline-primary" href="{% url 'groceries:new' %}">新建设备</a>
{% endif %}
</div>
{% endblock %}
{% block ac3 %}active{% endblock %}

groceries/templates/groceries/lend.html
{% extends 'nav.html' %}

{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block subtitle %}
{% if f == "lend" %}
-借出设备
{% endif %}
{% if f == "new" %}
-新建设备
{% endif %}
{% endblock %}
{% block ac3 %}active{% endblock %}
{% block main %}
<div class="row">
  <div class="col-md-12">
      <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "提交" type="submit" class="btn btn-primary" %}
  </form>
  </div>
</div>
{% endblock %}