courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>/', views.detail, name='detail'),
    path('<int:course_id>/groups', views.groups, name='groups'),
    path('<int:course_id>/ghistory', views.ghistory, name='ghistory'),
    path('<int:course_id>/schedule', views.ScheduleListView.as_view(), name='schedules'),
    path('<int:course_id>/upload', views.courseUploadFile, name='upload'),
    path('<int:course_id>/files', views.courseFiles, name='files'),
    path('files/del/<int:file_id>', views.delFile, name='delFile'),
    path('join/<int:group_id>/', views.joinGroup, name='joinGroup'),
    path('leave/<int:group_id>/', views.leaveGroup, name='leaveGroup'),
    path('group/<int:group_id>/', views.groupDetail, name='gdetail'),
    path('group/del/<int:group_id>/', views.delGroup, name='delGroup'),
    path('group/add/<int:course_id>/', views.AddGroupView.as_view(), name='addGroup'),
    path('group/update/<int:group_id>/<str:stu_id>/', views.updateSeat, name='updateSeat'),
    path('log/add/<int:group_id>/', views.logAdd, name='logAdd'),
    path('log/<int:group_id>/', views.logView, name='logView'),
    path('log/confirm/<int:log_id>/', views.logConfirm, name='logConfirm'),
    path('schedule/add/<int:course_id>/', views.AddScheduleView.as_view(), name='addSchedule'),
    path('schedule/del/<int:sche_id>/', views.delSchedule, name='delSchedule'),
    path('schedule/update/<int:pk>/', views.UpdateScheduleView.as_view(), name='updateSchedule'),
    path('eva/<int:group_id>/<str:stu_id>/', views.evaView, name='evaView'),
    path('eva/add/<int:group_id>/<str:stu_id>/', views.AddStudentEvaView.as_view(), name='addEva'),
    path('eva/day/<int:group_id>/', views.evaDayView, name='evaDay'),
    path('eva/del/<int:pk>/', views.delEva, name='delEva'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('rooms/<int:room_id>/', views.roomDetail, name='roomDetail'),
    path('update/<int:pk>/', views.CourseUpdateView.as_view(), name='courseUpdate'),
]

groceries/urls.py
from django.urls import path
from . import views

app_name = 'groceries'
urlpatterns = [
    path('', views.index, name='index'),
    path('lend/<int:lend_id>/', views.lendItem, name='lend'),
    path('hist/<int:lend_id>/', views.itemHist, name='hist'),
    path('edit/<int:lend_id>/', views.editItem, name='edit'),
    path('del/<int:lend_id>/', views.delItem, name='del'),
    path('new/', views.newItem, name='new'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('logout/', views.logout_view, name='logout'),
]

meeting/urls.py
from django.urls import path
from . import views

app_name = 'meeting'
urlpatterns = [
    path('', views.index, name='index'),
    path('agenda/list/<int:room_id>/', views.agenda_list, name='agenda_list'),
    path('agenda/add/<int:room_id>/', views.agenda_add, name='agenda_add'),
    path('agenda/view/<int:agenda_id>/', views.agenda_view, name='agenda_view'),
    path('agenda/del/<int:agenda_id>/', views.agenda_del, name='agenda_del'),
    path('agenda/confirm/<int:agenda_id>/', views.agenda_confirm, name='agenda_confirm'),
]

mystuff/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('items/', include('groceries.urls')),
    path('meeting/', include('meeting.urls')),
    path('courses/', include('courses.urls')),
    path('linux/', include('linux.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

MEETING_ADMIN = 1  # 会议室确认权限
LAB_ADMIN = 2      # 实验室管理员

class Teacher(models.Model):

    class Meta:
        verbose_name="教师"
        verbose_name_plural="教师"

    name = models.CharField(max_length=200, verbose_name="姓名")
    uid = models.CharField(max_length=10, verbose_name="工作证号")
    perm = models.IntegerField(default=0, verbose_name="权限") # web permissions

    def is_meeting_admin(self):
        return self.perm & MEETING_ADMIN

    @staticmethod
    def is_meeting_admin(request):
        if 'userperm' in request.session:
            return request.session['userperm'] & MEETING_ADMIN
        return False

    @staticmethod
    def is_lab_admin(request):
        if 'userperm' in request.session:
            return request.session['userperm'] & LAB_ADMIN
        return False

home/views.py
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from courses.models import SchoolYear, CourseGroup, StudentGroup, StudentHist
from linux.models import Survey
from .models import Teacher

import hashlib
import requests
import json
from datetime import timedelta
from django.utils import timezone

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'home/login.html');
    if not 'realname' in request.session:
        return render(request, 'home/login.html');
    sy = SchoolYear.objects.all().order_by('-start');
    if sy.count() == 0:
        raise Http404("没有定义学期");
    year = sy.first() # current school season
    cg = CourseGroup.objects.filter(year=year) # all lab sessions
    course_list = []
    if request.user.username == 'Student':
        for g in cg:
            sg = StudentGroup.objects.filter(group=g,stu_id=request.session['schoolid'])
            if sg.count() > 0:
                sv = Survey.objects.filter(course=g.course)
                if (sv.count() > 0):
                    g.survey = 1
                else:
                    g.survey = 0
                now = timezone.now() + timedelta(hours=-5) # 五小时以内
                sh = StudentHist.objects.filter(group=g, stu_id=request.session['schoolid'],confirm=1,fin_time__gte=now)
                if (sh.count() > 0):
                    g.complete = 1  # 每天只能完成一个实验一次，其他时间也可以重复记录
                else:
                    g.complete = 0
                course_list.append(g)
    else:
        for g in cg:
            if g.tea_name == request.session['realname']:
                course_list.append(g);
    return render(request, 'home/index.html', {'schoolyear':year, 'courses':course_list})

def auth(request):
    def get_client_ip(request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip
    KEY=settings.IAAA_KEY
    ip=get_client_ip(request)
    token=request.GET.get('token', '')
    if settings.DEBUG:
        if (token == 'Student') or (token == 'Teacher'):
            u = User.objects.filter(username=token)
            if u.count() == 0:
                raise Http404('Invalid login')
            login(request, u.first())
            request.session['realname'] = request.GET.get('name', '贾鸣')
            request.session['schoolid'] = request.GET.get('id', '123456')
            tea = Teacher.objects.filter(uid = request.session['schoolid'])
            if tea.count() > 0:
                request.session['userperm'] = tea.first().perm
            else:
                request.session['userperm'] = 0
            return HttpResponseRedirect('/')

    para='appId=EELABWeb&remoteAddr='+ip+'&token='+token+KEY
    m=hashlib.md5()
    m.update(para.encode('utf-8'))
    url='https://iaaa.pku.edu.cn/iaaa/svc/token/validate.do'
    payload={'appId': 'EELABWeb', 'remoteAddr': ip, 'token': token, 'msgAbs': m.hexdigest()}
    r=requests.get(url, params=payload)
    data=json.loads(r.text)
    if data['errCode'] != '0':
        return HttpResponseRedirect('/')
    uid=data['userInfo']['identityId']
    utp=data['userInfo']['identityType']
    user=None
    if utp=='学生':
        u=User.objects.filter(username='Student')
        if u.count() > 0:
            user = u.first()
    if utp=='职工':
        u=User.objects.filter(username=uid)
        if u.count() == 0:
            u=User.objects.filter(username='Teacher')
        if u.count() > 0:
            user = u.first()
    if user:
        login(request, user)
        request.session['realname'] = data['userInfo']['name']
        request.session['schoolid'] = uid
        tea = Teacher.objects.filter(uid = uid)
        if tea.count() > 0:
            request.session['userperm'] = tea.first().perm
        else:
            request.session['userperm'] = 0
    return HttpResponseRedirect('/')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title> {% block title %}{% endblock %}</title>
        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/mycss.css' %}">
    </head>

    <body class="bg-light {% block body_class %}{% endblock %}">

        {% block content %}{% endblock %}

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

home/templates/bootstrap.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    {% block bootstrap5_extra_head %}{% endblock %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block bootstrap5_extra_script %}{% endblock %}
{% endblock %}

home/templates/nav.html
{% extends "bootstrap.html" %}
{% load static %}

{% block title %}电子信息科学基础实验中心{% block subtitle %}{% endblock %}{% endblock %}
{% block body_class %}homepage{% endblock %}
{% block content %}
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark shadow">
  <div class="container-fluid">
  <a class="navbar-brand" href="/">电子信息科学基础实验中心</a>
   <button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
   <span data-feather="sidebar">菜单</span></button>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
    {% if user.is_authenticated %}
      <a class="nav-link" href="/logout/">退出登录</a>
    {% else %}
      <a class="nav-link" href="{% static 'html/login.html' %}">登录</a>
    {% endif %}
    </li>
  </ul>
  </div>
</nav>
<div class="container-fluid">
  {% block container %}
  <div class="row">
    <div class="col-md-3 col-lg-3 mt-3">
    <nav id="sidebarMenu" class="d-md-block bg-light collapse">
      <div class="mt-3 mx-5">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link {% block ac1 %}{% endblock %}" href="/">
            <span data-feather="check"></span>
            个人中心 
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link {% block ac2 %}{% endblock %}" href="{% url 'courses:index' %}">
            <span data-feather="sun"></span>
            全部课程
            </a>
          </li>
          {% if request.user.username == 'Teacher' %}
          <li class="nav-item">
            <a class="nav-link {% block ac3 %}{% endblock %}" href="{% url 'groceries:index' %}">
            <span data-feather="printer"></span>
            我的设备
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link {% block ac4 %}{% endblock %}" href="{% url 'meeting:index' %}">
            <span data-feather="calendar"></span>
            预订会议室
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link {% block ac5 %}{% endblock %}" href="{% url 'courses:rooms' %}">
            <span data-feather="activity"></span>
            全部实验室
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    </div>
    <div class="col-md-8 ml-sm-auto col-lg-8">
    <main role="main">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap justify-content-center pt-3 pb-2 mb-3 border-bottom">
      {% block main %}
      {% endblock %}
      </div>
    </main>
    </div>
  </div>
  {% endblock %}
</div>
{% endblock %}
{% block bootstrap5_extra_script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script> feather.replace() </script>
{% block morescripts %}
{% endblock %}
{% endblock %}