courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>/', views.detail, name='detail'),
    path('<int:course_id>/groups', views.groups, name='groups'),
    path('<int:course_id>/ghistory', views.ghistory, name='ghistory'),
    path('<int:course_id>/schedule', views.ScheduleListView.as_view(), name='schedules'),
    path('<int:course_id>/upload', views.courseUploadFile, name='upload'),
    path('<int:course_id>/files', views.courseFiles, name='files'),
    path('files/del/<int:file_id>', views.delFile, name='delFile'),
    path('join/<int:group_id>/', views.joinGroup, name='joinGroup'),
    path('leave/<int:group_id>/', views.leaveGroup, name='leaveGroup'),
    path('group/<int:group_id>/', views.groupDetail, name='gdetail'),
    path('group/del/<int:group_id>/', views.delGroup, name='delGroup'),
    path('group/add/<int:course_id>/', views.AddGroupView.as_view(), name='addGroup'),
    path('group/update/<int:group_id>/<str:stu_id>/', views.updateSeat, name='updateSeat'),
    path('log/add/<int:group_id>/', views.logAdd, name='logAdd'),
    path('log/<int:group_id>/', views.logView, name='logView'),
    path('log/confirm/<int:log_id>/', views.logConfirm, name='logConfirm'),
    path('schedule/add/<int:course_id>/', views.AddScheduleView.as_view(), name='addSchedule'),
    path('schedule/del/<int:sche_id>/', views.delSchedule, name='delSchedule'),
    path('schedule/update/<int:pk>/', views.UpdateScheduleView.as_view(), name='updateSchedule'),
    path('eva/<int:group_id>/<str:stu_id>/', views.evaView, name='evaView'),
    path('eva/add/<int:group_id>/<str:stu_id>/', views.AddStudentEvaView.as_view(), name='addEva'),
    path('eva/day/<int:group_id>/', views.evaDayView, name='evaDay'),
    path('eva/del/<int:pk>/', views.delEva, name='delEva'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('rooms/<int:room_id>/', views.roomDetail, name='roomDetail'),
    path('update/<int:pk>/', views.CourseUpdateView.as_view(), name='courseUpdate'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('logout/', views.logout_view, name='logout'),
]

linux/urls.py
from django.urls import path
from . import views

app_name = 'linux'
urlpatterns = [
    path('', views.index, name='index'),
    path('pubkey', views.pubkey, name='pubkey'),
    path('gituser', views.gituser, name='gituser'),
    path('resetuser', views.resetUser, name='resetUser'),
    path('diff', views.showDiff, name='showDiff'),
    path('vimcp', views.copyViHW, name='vimcp'),
]

mystuff/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('items/', include('groceries.urls')),
    path('meeting/', include('meeting.urls')),
    path('courses/', include('courses.urls')),
    path('linux/', include('linux.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

MEETING_ADMIN = 1  # 会议室确认权限
LAB_ADMIN = 2      # 实验室管理员

class Teacher(models.Model):

    class Meta:
        verbose_name="教师"
        verbose_name_plural="教师"

    name = models.CharField(max_length=200, verbose_name="姓名")
    uid = models.CharField(max_length=10, verbose_name="工作证号")
    perm = models.IntegerField(default=0, verbose_name="权限") # web permissions

    def is_meeting_admin(self):
        return self.perm & MEETING_ADMIN

    @staticmethod
    def is_meeting_admin(request):
        if 'userperm' in request.session:
            return request.session['userperm'] & MEETING_ADMIN
        return False

    @staticmethod
    def is_lab_admin(request):
        if 'userperm' in request.session:
            return request.session['userperm'] & LAB_ADMIN
        return False

home/views.py
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from courses.models import SchoolYear, CourseGroup, StudentGroup, StudentHist
from linux.models import Survey
from .models import Teacher

import hashlib
import requests
import json
from datetime import timedelta
from django.utils import timezone

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'home/login.html');
    if not 'realname' in request.session:
        return render(request, 'home/login.html');
    sy = SchoolYear.objects.all().order_by('-start');
    if sy.count() == 0:
        raise Http404("没有定义学期");
    year = sy.first() # current school season
    cg = CourseGroup.objects.filter(year=year) # all lab sessions
    course_list = []
    if request.user.username == 'Student':
        for g in cg:
            sg = StudentGroup.objects.filter(group=g,stu_id=request.session['schoolid'])
            if sg.count() > 0:
                sv = Survey.objects.filter(course=g.course)
                if (sv.count() > 0):
                    g.survey = 1
                else:
                    g.survey = 0
                now = timezone.now() + timedelta(hours=-5) # 五小时以内
                sh = StudentHist.objects.filter(group=g, stu_id=request.session['schoolid'],confirm=1,fin_time__gte=now)
                if (sh.count() > 0):
                    g.complete = 1  # 每天只能完成一个实验一次，其他时间也可以重复记录
                else:
                    g.complete = 0
                course_list.append(g)
    else:
        for g in cg:
            if g.tea_name == request.session['realname']:
                course_list.append(g);
    return render(request, 'home/index.html', {'schoolyear':year, 'courses':course_list})

def auth(request):
    def get_client_ip(request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip
    KEY=settings.IAAA_KEY
    ip=get_client_ip(request)
    token=request.GET.get('token', '')
    if settings.DEBUG:
        if (token == 'Student') or (token == 'Teacher'):
            u = User.objects.filter(username=token)
            if u.count() == 0:
                raise Http404('Invalid login')
            login(request, u.first())
            request.session['realname'] = request.GET.get('name', '贾鸣')
            request.session['schoolid'] = request.GET.get('id', '123456')
            tea = Teacher.objects.filter(uid = request.session['schoolid'])
            if tea.count() > 0:
                request.session['userperm'] = tea.first().perm
            else:
                request.session['userperm'] = 0
            return HttpResponseRedirect('/')

    para='appId=EELABWeb&remoteAddr='+ip+'&token='+token+KEY
    m=hashlib.md5()
    m.update(para.encode('utf-8'))
    url='https://iaaa.pku.edu.cn/iaaa/svc/token/validate.do'
    payload={'appId': 'EELABWeb', 'remoteAddr': ip, 'token': token, 'msgAbs': m.hexdigest()}
    r=requests.get(url, params=payload)
    data=json.loads(r.text)
    if data['errCode'] != '0':
        return HttpResponseRedirect('/')
    uid=data['userInfo']['identityId']
    utp=data['userInfo']['identityType']
    user=None
    if utp=='学生':
        u=User.objects.filter(username='Student')
        if u.count() > 0:
            user = u.first()
    if utp=='职工':
        u=User.objects.filter(username=uid)
        if u.count() == 0:
            u=User.objects.filter(username='Teacher')
        if u.count() > 0:
            user = u.first()
    if user:
        login(request, user)
        request.session['realname'] = data['userInfo']['name']
        request.session['schoolid'] = uid
        tea = Teacher.objects.filter(uid = uid)
        if tea.count() > 0:
            request.session['userperm'] = tea.first().perm
        else:
            request.session['userperm'] = 0
    return HttpResponseRedirect('/')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

home/templates/home/index.html
{% extends "nav.html" %}
{% load static %}
{% block ac1 %}active{% endblock %}
{% block main %}
<div class="container">
<div class="row">
    <div class="col-md-12"><div class="card border-info"><div class="card-body">
   {{ request.session.realname }} 您好！<br>
   <script src="{% static 'js/weekcode.js' %}"></script>
   <script type="text/javascript">
    var date = new Date();
    document.write("今天是：" + date.getFullYear() + "年" + (date.getMonth() + 1) + "月" + date.getDate() + "日" + " 星期" + "日一二三四五六".charAt(date.getDay()));

   </script>
   ，现在是{{ schoolyear.get_status }}
    </div></div></div>
</div>
<br>
<div class="row">
  <div class="col-md-6">
    <div class="card border-primary mb-3">
    <div class="card-header alert-warning">
      本学期课程
    </div>
    <div class="card-body">
    {% if courses %}
     <table class="table table-borderless">
         <tr><th>课程名称</th><th>上课时间</th><th>上课地点</th></tr>
         {% for c in courses %}
         <tr> <td><a href="{% url 'courses:detail' c.course.id %}">{{ c.course }}</a></td>
             <td><script>weekcode("{{ c.week }}")</script></td>
             <td>{{ c.room }}
                 {% if request.user.username == 'Student' %}
                     {% if c.survey == 1 %}
                     <a class="btn btn-outline-danger" href="{% url 'linux:index' %}">课程仪表盘</a>
                     {% else %}
                     {% if c.complete == 0 %}
                     <a class="btn btn-outline-danger" href="{% url 'courses:logAdd' c.id %}">实验记录</a>
                     {% endif %}
                     {% endif %}
                 {% else %}
                 <a class="btn btn-outline-danger" href="{% url 'courses:logView' c.id %}">查看名单</a>
                 {% endif %}
             </td>
      </tr>
         {% endfor %}
     </table>
    {% else %}
    <p class="card-text">没有已选课程</p>
    {% endif %}
    </div>
    </div>
  </div>
</div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted mt-3">
        需要帮助：请感兴趣的同学为网站提交代码（<a href="https://github.com/setarcos/DjangoLab">Github</a>）
        </p>
      </div>
    </footer>
</div>
{% endblock %}

home/templates/home/login.html
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>重定向</title>
<body>
    <div align="center" style="color:#BB0000;font-family:Microsoft Yahei;font-size: 24px; font-weight: bold; margin: 20px 20px 20px 20px;">
<p>正在转向北京大学身份认证系统......</p>
</div>
<script language=javascript>
		document.write("<form action='https://iaaa.pku.edu.cn/iaaa/oauth.jsp' method=post name='formx1' style='display:none'>");
		document.write("<input type=hidden name='appID' value='EELABWeb'>");
		document.write("<input type=hidden name='appName' value='基础教学实验中心'>");
		document.write("<input type=hidden name='redirectUrl' value='http://162.105.91.8/auth/'>");
		document.write("</form>");
		setTimeout("document.formx1.submit();",1000);
	</script>
</body>
</html>