courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>/', views.detail, name='detail'),
    path('<int:course_id>/groups', views.groups, name='groups'),
    path('<int:course_id>/ghistory', views.ghistory, name='ghistory'),
    path('<int:course_id>/schedule', views.ScheduleListView.as_view(), name='schedules'),
    path('<int:course_id>/upload', views.courseUploadFile, name='upload'),
    path('<int:course_id>/files', views.courseFiles, name='files'),
    path('files/del/<int:file_id>', views.delFile, name='delFile'),
    path('join/<int:group_id>/', views.joinGroup, name='joinGroup'),
    path('leave/<int:group_id>/', views.leaveGroup, name='leaveGroup'),
    path('group/<int:group_id>/', views.groupDetail, name='gdetail'),
    path('group/del/<int:group_id>/', views.delGroup, name='delGroup'),
    path('group/add/<int:course_id>/', views.AddGroupView.as_view(), name='addGroup'),
    path('group/update/<int:group_id>/<str:stu_id>/', views.updateSeat, name='updateSeat'),
    path('log/add/<int:group_id>/', views.logAdd, name='logAdd'),
    path('log/<int:group_id>/', views.logView, name='logView'),
    path('log/confirm/<int:log_id>/', views.logConfirm, name='logConfirm'),
    path('schedule/add/<int:course_id>/', views.AddScheduleView.as_view(), name='addSchedule'),
    path('schedule/del/<int:sche_id>/', views.delSchedule, name='delSchedule'),
    path('schedule/update/<int:pk>/', views.UpdateScheduleView.as_view(), name='updateSchedule'),
    path('eva/<int:group_id>/<str:stu_id>/', views.evaView, name='evaView'),
    path('eva/add/<int:group_id>/<str:stu_id>/', views.AddStudentEvaView.as_view(), name='addEva'),
    path('eva/day/<int:group_id>/', views.evaDayView, name='evaDay'),
    path('eva/del/<int:pk>/', views.delEva, name='delEva'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('rooms/<int:room_id>/', views.roomDetail, name='roomDetail'),
    path('update/<int:pk>/', views.CourseUpdateView.as_view(), name='courseUpdate'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('logout/', views.logout_view, name='logout'),
]

mystuff/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('items/', include('groceries.urls')),
    path('meeting/', include('meeting.urls')),
    path('courses/', include('courses.urls')),
    path('linux/', include('linux.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

class Course(models.Model):
    class Meta:
        verbose_name="课程"
        verbose_name_plural="课程"
    name = models.CharField(max_length=100, verbose_name="课程名")
    ename = models.CharField(max_length=200, verbose_name="课程英文名")
    ccode = models.CharField(max_length=20, verbose_name="课程号,学分,学时")
    term = models.IntegerField(default=0, verbose_name="开课学期")
    tea_id = models.CharField(max_length=10, verbose_name="负责人ID") # 负责人 ID
    tea_name = models.CharField(max_length=50, verbose_name="授课教师") # 可以输入多个教师名
    intro = RichTextField(verbose_name="课程大纲")
    mailbox=models.CharField(max_length=200, verbose_name="联系邮箱")
    def __str__(self):
        return self.name

class LabRoom(models.Model):
    class Meta:
        verbose_name="实验室"
        verbose_name_plural="实验室"
    name = models.CharField(max_length=10, verbose_name="房间号")
    cname = models.CharField(max_length=30, verbose_name="实验室名称")
    manager = models.CharField(max_length=10, verbose_name="负责人")
    def __str__(self):
        return self.name

class SchoolYear(models.Model):
    class Meta:
        verbose_name="学年"
        verbose_name_plural="学年"
    name = models.CharField(max_length=10, verbose_name="学期")
    start = models.DateField(default=timezone.now().date(), verbose_name="起始时间")
    end = models.DateField(default=timezone.now().date(), verbose_name="结束时间")
    def __str__(self):
        return self.name

    def get_wcount(self):
        now = timezone.now().date();
        return int((now - self.start).days / 7 + 1)

    @staticmethod
    def get_week():
        sy = SchoolYear.objects.all().order_by('-start');
        if sy.count() == 0:
            return -1
        return sy.first().get_wcount();

    @staticmethod
    def get_current_year():
        sy = SchoolYear.objects.all().order_by('-start');
        return sy.first()

    def get_status(self):
        now = timezone.now().date();
        if (now < self.start) or (now > self.end):
            return "假期"
        return self.name + f"学期，第 {self.get_wcount()} 周"

class CourseSchedule(models.Model):
    class Meta:
        verbose_name="课程安排"
        verbose_name_plural="课程安排"
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    week = models.IntegerField(default=0, verbose_name="周")
    name = models.CharField(max_length=20, verbose_name="实验内容")
    require = models.CharField(max_length=50, verbose_name="实验要求", default="")
    def __str__(self):
        return self.name

class CourseGroup(models.Model):
    class Meta:
        verbose_name="课程分组"
        verbose_name_plural="课程分组"
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    # 两位数，第一位代表星期，第二位代表上午下午和晚上，例如 72 代表周日晚上，0 代表特殊时间安排
    week = models.IntegerField(default=0, verbose_name="上课时间")
    room = models.ForeignKey(LabRoom, on_delete=models.CASCADE, verbose_name="上课地点")
    tea_name = models.CharField(max_length=10, verbose_name="授课教师")
    year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE, verbose_name="学年")
    limit = models.IntegerField(default=15, verbose_name="人数限制")
    lag = models.IntegerField(default=0, verbose_name="落后进度周数")

class StudentGroup(models.Model):
    group = models.ForeignKey(CourseGroup, on_delete=models.CASCADE)
    stu_id = models.CharField(max_length=10, verbose_name="学号")
    stu_name = models.CharField(max_length=10, verbose_name="姓名")
    seat = models.IntegerField(default=0, verbose_name="座位")

class StudentHist(models.Model):
    stu_id = models.CharField(max_length=10, verbose_name="学号")
    stu_name = models.CharField(max_length=10, verbose_name="姓名")
    group = models.ForeignKey(CourseGroup, on_delete=models.SET_NULL, verbose_name="课程名称", null=True)
    room = models.ForeignKey(LabRoom, on_delete=models.CASCADE, verbose_name="上课地点")
    seat = models.IntegerField(default=0, verbose_name="座位")
    lab_name = models.CharField(max_length=20, verbose_name="实验内容")
    note = models.CharField(max_length=50, verbose_name="自记录")
    tea_note =models.CharField(default="", max_length=50, verbose_name="教师记录")
    tea_name = models.CharField(max_length=10, verbose_name="教师姓名")
    fin_time = models.DateTimeField(default='2018-01-01 00:00:00', verbose_name="日期")  # confirm 时间
    confirm = models.IntegerField(default=0, verbose_name="确认")

class StudentLog(models.Model): # StudentEva might be a better name, since I use a lot eva to distinguish it from StudentHist
    group = models.ForeignKey(CourseGroup, on_delete=models.CASCADE)
    stu_id = models.CharField(max_length=10, verbose_name="学号")
    tea_name = models.CharField(max_length=10, verbose_name="教师")
    note = models.CharField(default="", max_length=100, verbose_name="记录内容")
    note_time = models.DateTimeField(verbose_name="时间")

class CourseFiles(models.Model):
    class Meta:
        verbose_name="课程资料"
        verbose_name_plural="课程资料"
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    fname = models.CharField(max_length=100, verbose_name="文件名")
    finfo = models.CharField(max_length=100, verbose_name="文件说明")

courses/forms.py
from django import forms
from .models import LabRoom, CourseGroup, Course, CourseSchedule, StudentLog, CourseFiles
from bootstrap_modal_forms.forms import BSModalModelForm
from ckeditor.widgets import CKEditorWidget

class StuLabForm(forms.Form):
    stu_id = forms.CharField(
        label='学号',
        widget=forms.TextInput(attrs={'readonly':True}),
        )
    stu_name = forms.CharField(
        label='姓名',
        widget=forms.TextInput(attrs={'readonly':True}),
        )
    room = forms.ModelChoiceField(
        queryset=LabRoom.objects.all(),
        label='房间号',
        )
    seat = forms.IntegerField(
        max_value = 100,
        min_value = 1,
        label='座位号',
        )
    lab_name = forms.CharField(
        label='实验名称',
        )
    switch = forms.BooleanField(
        label='设备关机，烙铁断电',
        )
    table = forms.BooleanField(
        label='整理桌面',
        )
    note = forms.CharField(
        required=False,
        label='设备问题',
        )

class GroupForm(BSModalModelForm):
    nweek = forms.ChoiceField(
            label='星期',
            choices=((0, "不指定"), (1, "周一"), (2, "周二"), (3, "周三"), (4, "周四"),
                (5, "周五"), (6, "周六"), (7, "周日")),
            )
    npart = forms.ChoiceField(
            label='时间',
            choices=((0, "上午"), (1, "下午"), (2, "晚上"), (3, "后段下午"), (4, "后段晚上")),
            )
    modal_title = "增加时段"

    class Meta:
        model = CourseGroup
        fields = ['room', 'tea_name', 'limit']

class ScheduleForm(BSModalModelForm):
    require = forms.CharField(
            required = False,
            label='具体要求',
            )
    modal_title = "增加实验内容"

    class Meta:
        model = CourseSchedule
        fields = ['week', 'name', 'require']

class StudentEvaForm(BSModalModelForm):
    modal_title = "增加学生评价"
    stu_name = forms.CharField(
        label='姓名',
        widget=forms.TextInput(attrs={'readonly':True}),
        )

    forget = forms.BooleanField(
            label='学生未填写记录离开',
            required = False,
            )
    note = forms.CharField(
            label='记录内容',
            required = False,
            )
    class Meta:
        model = StudentLog
        fields = ['note', 'stu_name']

    def clean(self):
        cleaned_data = super(StudentEvaForm, self).clean()
        forget = cleaned_data.get('forget')
        note = cleaned_data.get('note')
        if (forget == False) and (note == ''):
            raise forms.ValidationError("必须填写内容")
        return cleaned_data

class EvaDayForm(forms.Form):
    edate = forms.DateField(
        label='实验时间',
        )
    nweek = forms.IntegerField(
        label='上课周次',
        )

class LabRoomQueryForm(forms.Form):
    sdate = forms.DateField(
        label='开始时间',
        )
    edate = forms.DateField(
        label='结束时间',
        )

class CourseForm(forms.ModelForm):
    term = forms.ChoiceField(
            label='开课学期',
            choices=((0, "春季"), (1, "秋季"), (2, "暑期")),
            )
    class Meta:
        model = Course
        exclude = ['ccode','tea_id']

class SeatForm(forms.Form):
    seat2 = forms.IntegerField(
        label = '新座位号',
        )

class UploadForm(forms.Form):
    finfo = forms.CharField(
        label = '文件描述'
        )
    file = forms.FileField(
        label = '文件'
        )
    course = None

    def clean(self):
        cleaned_data = super().clean()
        up_file = cleaned_data.get('file')
        files = CourseFiles.objects.filter(course=self.course, fname=up_file.name)
        if (files.count() > 0):
            raise forms.ValidationError("文件已经在服务器存在")
        return cleaned_data;

courses/templates/courses/add_schedule.html
{% load bootstrap4 %}
{% bootstrap_messages %}
<form method="post" action="">
{% csrf_token %}
 <div class="modal-header">
    <h5 class="modal-title">增加内容</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% bootstrap_form form %}
  </div>

  <div class="modal-footer">
    {% buttons %}
    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
    <button type="submit" class="btn btn-primary">增加</button>
    {% endbuttons %}
  </div>

</form>

courses/templates/courses/course_update.html
{% extends "nav.html" %}

{% load django_bootstrap5 %}

{% bootstrap_messages %}
{% block subtitle %}-修改课程信息{% endblock %}
{% block main %}
<div class="row">
  <div class="col-md">
      <form action="" method="post">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% bootstrap_button "提交" type="submit" class="btn btn-primary" %}
      </form>
  </div>
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/detail.html
{% extends 'nav.html' %}
 
{% block subtitle %}-课程详情{% endblock %}

{% block main %}
<script language="JavaScript">
function expendcode(code, idx)
{
    document.write(code.split(",")[idx]);
}
function termcode(term)
{
    if (term == 0) document.write("春季");
    else if (term == 1) document.write("秋季");
    else document.write("暑期");
}
</script>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active">课程详情</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:groups' course.id %}">分组信息</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:schedules' course.id %}">时间安排</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:files' course.id %}">课程资料</a></li>
  </ul>
  <div class="tab-content" id="course-tabs">
    <table class="table table-course">
       <tr><th width="10%">课程名称</th> <td colspan="7"> {{ course.name }} </td> </tr>
       <tr><th>英文名称</th> <td colspan="7"> {{ course.ename }} </td></tr>
       <tr><th>课程编号</th> <td width="15%"> <script> expendcode("{{ course.ccode }}", 0) </script></td>
           <th width="12.5%">学分</th> <td width="12.5%"> <script> expendcode("{{ course.ccode }}", 1) </script></td>
           <th width="12.5%">课时</th> <td width="12.5%"> <script> expendcode("{{ course.ccode }}", 2) </script></td>
           <th width="12.5%">学期</th> <td> <script> termcode({{ course.term }}) </script></td></tr>
       <tr><th>授课教师</th> <td colspan="3"> {{ course.tea_name }} </td>
           <th>联系方式</th> <td colspan="3"> {{ course.mailbox }} </td></tr>
       <tr><th>课程大纲</th> <td colspan="7"> {{ course.intro|safe }}
           {% if request.session.schoolid == course.tea_id %}
           <a class="btn btn-outline-primary" href="{% url 'courses:courseUpdate' course.id %}">修改</a>
           {% endif %}
           </td></tr>
    </table>
  </div>
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/eva_day.html
{% extends 'nav.html' %}
  
{% block subtitle %}-学生记录{% endblock %}
{% block main %}

{% load django_bootstrap5 %}
{% bootstrap_messages %}
<div class="container">
    <div class="panel-heading">学生记录</div>
      <form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-4"> <b>{{ form.edate.label_tag }}</b> - {{ form.edate }}</div>
        <div class="col-sm-4"> <b>{{ form.nweek.label_tag }}</b> - {{ form.nweek}} </div>
        <div class="col-sm-4">
        {% bootstrap_button "查询" type="submit" class="btn btn-primary" %}
        </div>
    </div>
      </form>
   <table class="table table-course">
       <tr><th class="d-none d-lg-table-cell">学号</th><th>学生姓名</th><th>座位</th><th>记录</th></tr>
       {% for g in hist %}
       <tr><td class="d-none d-lg-table-cell">{{ g.stu_id}}</td>
           <td><a href="{% url 'courses:evaView' g.group.id g.stu_id %}">{{ g.stu_name }}</a></td>
           <td>{{ g.seat }}</td><td>
               <table class="table table-course">
                   {% for n in g.log %}
                   <tr><td>{{ n.note }}</td><td class="d-none d-lg-table-cell" width="35%">
                        {% if show_date %}
                            {{ n.note_time|date:"Y-m-d H:i:s" }}
                        {% else %}
                            {{ n.note_time|date:"H:i:s" }}
                        {% endif %}
                   </td></tr>
                   {% endfor %}
               </table>
        </td></tr>
       {% endfor %}
   </table>
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/form_temp.html
{% load django_bootstrap5 %}
{% bootstrap_messages %}
<form method="post" action="">
{% csrf_token %}
  <div class="modal-header">
     <h5 class="modal-title">{{ form.modal_title }}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
    </button>
  </div>

  <div class="modal-body">
    {% bootstrap_form form %}
  </div>

  <div class="modal-footer">
      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">关闭</button>
      {% bootstrap_button "增加" type="submit" class="btn btn-primary" %}
  </div>

</form>

courses/templates/courses/ghistory.html
{% extends 'nav.html' %}
{% load static %}
 
{% block subtitle %}-课程分组历史{% endblock %}

{% block main %}
<script src="{% static 'js/weekcode.js' %}"></script>

<div class="container">
      {% if group %}
      <center><h2>课程名称：{{ course.name }}</h2></center>
      <table class = "table table-course table-striped">
          <tr><th>学年</th><th>时间</th><th>地点</th><th>任课教师</th><th>人数上限</th><th>操作</th></tr>
        {% for p in group %}
        <tr><td>{{ p.year }}</td><td><script>weekcode("{{ p.week }}") </script></td><td>{{ p.room }}</td>
                    <td>{{ p.tea_name }}</td><td>{{ p.limit }}</td>
                    <td>
              {% if request.user.username == 'Teacher' %}
              <a class="btn btn-outline-primary" href="{% url 'courses:gdetail' p.id %}">查看</a>
              <a class="btn btn-outline-primary" href="{% url 'courses:evaDay' p.id %}">评阅</a>
              {% endif %}
              </td>
          </tr>
        {% endfor %}
      </table>
      {% endif %}
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/group_detail.html
{% extends 'nav.html' %}
  
{% block subtitle %}-成员列表{% endblock %}

{% block main %}

<div class="container">
  <div class="panel-heading"> 成员列表</div>
  {% if group %}
   <table class="table table-course">
       <tr><th>学号</th><th>姓名</th><th>座位</th></tr>
       {% for g in group %}
       <tr{% if g.stu_id == request.session.schoolid %} class="table-success"{% endif %}>
           <td>{{ g.stu_id }}</td>
      {% if request.user.username == 'Teacher' %}
           <td><a href="{% url 'courses:evaView' g.group.id g.stu_id %}">{{ g.stu_name }}</a></td>
      {% else %}
           <td>{{ g.stu_name }}</td>
      {% endif %}
           <td>{{ g.seat }}</td></tr>
       {% endfor %}
   </table>
  {% else %}
    <p> 还没有人选择这个时段 </p>
  {% endif %}
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/groups.html
{% extends 'nav.html' %}
{% load static %}
 
{% block subtitle %}-课程详情{% endblock %}

{% block main %}
<script src="{% static 'js/weekcode.js' %}"></script>
<script language="JavaScript">
function SureDel(delurl)
{
	if (confirm("确定要删除这条记录?")){
        location = delurl;
	}
}
</script>

<div class="container">
  {% include 'courses/message.html' %}
  <ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:detail' course.id %}">课程详情</a></li>
    <li class="nav-item"><a class="nav-link active">分组信息</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:schedules' course.id %}">时间安排</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'courses:files' course.id %}">课程资料</a></li>
  </ul>
  <div class="tab-content" id="course-tabs">
      {% if group %}
      <table class = "table table-course table-striped">
          <tr><th>时间</th><th>地点</th><th>任课教师</th><th>人数上限</th><th>操作</th></tr>
        {% for p in group %}
            <tr><td><script>weekcode("{{ p.week }}") </script></td><td>{{ p.room }}</td>
                    <td>{{ p.tea_name }}</td><td>{{ p.limit }}</td>
                    <td>
                {% if request.user.username == 'Student' %}
                  {% if p.has_me == 1 %}
                  <a class="btn btn-outline-danger" href="{% url 'courses:leaveGroup' p.id %}">退出</a>
                  {% else %}
                  <a class="btn btn-outline-primary" href="{% url 'courses:joinGroup' p.id %}">选择</a>
                  {% endif %}
                {% endif %}
                {% if request.session.schoolid == course.tea_id %}
                  <a class="btn btn-outline-danger" href="javascript:SureDel('{% url 'courses:delGroup' p.id %}');">删除</a>
                {% endif %}
              &nbsp;&nbsp;
              {% if request.user.username == 'Student' %}
              <a class="btn btn-outline-primary" href="{% url 'courses:gdetail' p.id %}">查看</a>
              {% else %}
              <a class="btn btn-outline-primary" href="{% url 'courses:logView' p.id %}">查看</a>
              <a class="btn btn-outline-primary" href="{% url 'courses:evaDay' p.id %}">评阅</a>
              {% endif %}
              </td>
          </tr>
        {% endfor %}
      </table>
      {% endif %}
  </div>
{% if request.session.schoolid == course.tea_id %}
<!-- Create book button -->
<button id="add-group" class="btn btn-primary" type="button" name="button">增加</button>
<a class="btn btn-outline-primary" href="{% url 'courses:ghistory' course.id %}">历史</a>
{% endif %}
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock %}
{% block ac2 %}active{% endblock %}
{% block morescripts %}
<script src="{% static 'js/bootstrap5.modal.forms.js' %}"></script>
<script language="JavaScript">
document.addEventListener('DOMContentLoaded', (e) => {
  modalForm(document.getElementById('add-group'), {
    formURL: "{% url 'courses:addGroup' course.id %}",
    isDeleteForm: false
  })
});
</script>
{% endblock %}

courses/templates/courses/index.html
{% extends 'nav.html' %}
  
{% block subtitle %}-课程列表{% endblock %}

{% block main %}
<script language="JavaScript">
function expendcode(code)
{
    document.write(code.replace(/,/g, "</td><td>"));
}
function termcode(term)
{
    if (term == 0) document.write("春季");
    else if (term == 1) document.write("秋季");
    else document.write("暑期");
}
</script>

<div class="container">
  <div class="panel-heading"> 课程列表 </div>
  {% if course_list %}
   <table class="table table-course">
       <tr><th>课程名称</th><th>课程编号</th><th>学分</th><th>课时</th><th>学期</th><th>授课教师</th></tr>
       {% for c in course_list %}
       <tr> <td><a href="{% url 'courses:detail' c.id %}">{{ c.name }}</a></td>
        <td><script language="JavaScript"> expendcode("{{ c.ccode }}") </script> </td>
    <td><script language="JavaScript"> termcode({{ c.term }})</script>  <td> {{ c.tea_name }} </td>
    </tr>
       {% endfor %}
   </table>
  {% else %}
    <p> 还没有课程，请在 admin 页面创建新课程 </p>
  {% endif %}
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/log_add.html
{% extends "nav.html" %}

{% load django_bootstrap5 %}

{% bootstrap_messages %}

{% block subtitle %}-完成实验{% endblock %}
{% block main %}
<div class="row">
  <div class="col-md">
      <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "提交" type="submit" class="btn btn-primary" %}
      </form>
  </div>
</div>
{% endblock %}
{% block ac2 %}active{% endblock %}

courses/templates/courses/message.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

courses/templates/courses/room_detail.html
{% extends 'nav.html' %}
  
{% block subtitle %}-实验室日志{% endblock %}
{% block main %}

{% load django_bootstrap5 %}
{% bootstrap_messages %}
<div class="container">
    <div class="panel-heading">实验室日志（{% if number <= 100 %}{{ number }}{% else %}100/{{number}}{% endif %}条记录）</div>
      <form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-4">
            <b>{{ form.sdate.label_tag }}</b> - {{ form.sdate }}
        </div>
        <div class="col-sm-4">
            <b>{{ form.edate.label_tag }}</b> - {{ form.edate }}
        </div>
        <div class="col-sm-4">
            {% bootstrap_button "查询" type="submit" class="btn btn-primary" %}
        </div>
    </div>
      </form>
   <table class="table table-course">
       <tr><th>学号</th><th>姓名</th><th>座位</th><th>实验内容</th><th>备注</th><th>时间</th></tr>
       {% for g in hist %}
       <tr><td>{{ g.stu_id}}</td><td>{{ g.stu_name }}</td><td>{{ g.seat }}</td><td>{{ g.lab_name }}</td>
           <td>{{ g.note }}</td><td>{{ g.fin_time }}</td></tr>
       {% endfor %}
   </table>
</div>
{% endblock %}
{% block ac5 %}active{% endblock %}

courses/templates/courses/rooms.html
{% extends 'nav.html' %}
  
{% block subtitle %}-实验室列表{% endblock %}

{% block main %}

<div class="container">
   <div class="panel-heading">实验室列表</div>
   <table class="table table-course">
       <tr><th width="20%">房间号</th><th>实验室名称</th><th>负责人</th></tr>
       {% for g in object_list %}
       <tr><td>{% if perm %}<a href="{% url 'courses:roomDetail' g.id %}">{% endif %}
                   {{ g.name}}{% if perm %}</a>{% endif %}
           </td>
           <td>{{ g.cname }}</td><td>{{ g.manager }}</td></tr>
       {% endfor %}
   </table>
</div>
{% endblock %}
{% block ac5 %}active{% endblock %}

courses/templates/courses/upload.html
{% extends 'nav.html' %}

{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block subtitle %}
-添加文件
{% endblock %}
{% block ac2 %}active{% endblock %}
{% block main %}
<div class="row">
  <div class="col-md-12">
      <form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "提交" type="submit" class="btn btn-primary" %}
  </form>
  </div>
</div>
{% endblock %}